# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On macOS with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ERP_development
  username: postgres 
  password: 784512mbl
  host: localhost
  port: 5432 

 
test:
  <<: *default
  database: ERP_test
  username: postgres 
  password: 784512mbl
  host: localhost
  port: 5432


production:
  <<: *default
  database: ERP_production
  username: ERP
  password: <%= ENV["ERP_DATABASE_PASSWORD"] %>
