default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ERP_development
  username: postgres 
  password: 784512mbl
  host: localhost
  port: 5432 

 test:
  <<: *default
  database: ERP_test
  username: postgres 
  password: 784512mbl
  host: localhost
  port: 5432

production:
  <<: *default
  database: ERP_production
  username: ERP
  password: <%= ENV["ERP_DATABASE_PASSWORD"] %>
